name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Release:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    secrets:
      GH_PUSH_TOKEN        : ${{ secrets.GH_PUSH_TOKEN }}
      MAVEN_GPG_PASSPHRASE : ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY      : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME    : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_TOKEN       : ${{ secrets.SONATYPE_TOKEN }}
