name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Release:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    with:
      maven-flags: "-Denforcer.skip"
    secrets:
      GH_PUSH_TOKEN              : ${{ secrets.GH_PUSH_TOKEN }}
      GPG_PRIVATE_KEY            : ${{ secrets.GPG_PRIVATE_KEY }}
      MAVEN_GPG_PASSPHRASE       : ${{ secrets.GPG_PASSPHRASE }}
      SONATYPE_USERNAME          : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD          : ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_PUBLISH_USERNAME  : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PUBLISH_TOKEN     : ${{ secrets.SONATYPE_PASSWORD }}
